version: "3.3"
services:
  geoserver:
    image: kartoza/geoserver:2.23.0
    volumes:
      - geoserver-data:/opt/geoserver/data_dir
    restart: on-failure
    environment:
      - GEOSERVER_DATA_DIR=/opt/geoserver/data_dir
      - GEOWEBCACHE_CACHE_DIR=/opt/geoserver/data_dir/gwc
      - GEOSERVER_ADMIN_PASSWORD_FILE=/run/secrets/adminp
      - GEOSERVER_ADMIN_USER_FILE=/run/secrets/adminn
      - INITIAL_MEMORY=2G
      - MAXIMUM_MEMORY=4G
    #depends_on:
     # db:
      #  condition: service_healthy
    healthcheck:
      test: curl --fail -s http://localhost:8080/ || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3

  db:
    image: kartoza/postgis:15-3.3
    volumes:
      - geo-db-data:/var/lib/postgresql
    ports:
      - 32767:5432
    environment:
      - POSTGRES_DB=gisdb
      - POSTGRES_USER_FILE=/run/secrets/pgu
      - POSTGRES_PASS_FILE=/run/secrets/pgp
      - ALLOW_IP_RANGE=0.0.0.0/0
      # Add extensions you need to be enabled by default in the DB. Default are the five specified below
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting
      - RUN_AS_ROOT=false
    restart: on-failure
    healthcheck:
      test: "exit 0"

  nginx:
     image: nginx
     volumes:
       - ./sites-enabled:/etc/nginx/conf.d:ro
     logging:
       driver: json-file
       options:
         max-size: 200m
         max-file: '10'
     #depends_on:
      # - geoserver
     ports:
       - "8008:80"
secrets:
  adminp:
    file: adminp.txt
  adminn:
    file: adminn.txt
  pgu:
    file: pgu.txt
  pgp:
    file pgp.txt

volumes:
  # geoserver volumes
  geoserver-data:
  settings:
  # postgres volumes
  # dbbackups:
  # postgis-data:
  geo-db-data:

